# Generated by Django 5.2.3 on 2025-08-22 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0002_adminusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_add',
            name='Manufacturing_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
