# Generated by Django 5.2.3 on 2025-08-22 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0003_alter_product_add_manufacturing_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=100)),
                ('buyer_id', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('product_id', models.IntegerField()),
            ],
        ),
    ]
