# Generated by Django 5.2.3 on 2025-08-22 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0005_buyer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='buyer_id',
            new_name='buyer_username',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='buyer_name',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product_name',
        ),
    ]
