# Generated by Django 5.2.3 on 2025-08-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0006_rename_buyer_id_cart_buyer_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=100)),
                ('buyer_id', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('product_id', models.IntegerField()),
            ],
        ),
    ]
