# Generated by Django 5.2.3 on 2025-08-25 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0007_carts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=100)),
                ('vendor_id', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('product_brought', models.CharField(max_length=255)),
            ],
        ),
    ]
