# Generated by Django 5.2.3 on 2025-08-25 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0008_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_vendor',
            fields=[
                ('vendor_id', models.CharField(max_length=50, unique=True)),
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_brand', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Manufacturing_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('vendor_pwd', models.CharField(max_length=100)),
            ],
        ),
    ]
