# Generated by Django 5.2.3 on 2025-08-25 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0009_product_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='vendor_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
