# Generated by Django 5.2.3 on 2025-08-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0010_vendor_vendor_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_vendor',
            name='vendor_id',
            field=models.CharField(max_length=50),
        ),
    ]
